name: backend_dart
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # aquí van otras dependencias si tienes, o deja vacío si no hay ninguna
  
dev_dependencies:
  lints: ^3.0.0
